[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = ["...", "libicu-dev"]

[deploy]
startCommand = "cd src/VSMS.Web && dotnet VSMS.Web.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
